FROM cctbx-xfel


ADD --chown=user patches/logging.patch /img/opt/mamba/envs/psana_env/lib/python3.9/logging
RUN cd /img/opt/mamba/envs/psana_env/lib/python3.9/logging/ && \
        patch __init__.py logging.patch
