name: psana_env
channels:
 - lcls-i
 - conda-forge
 - cctbx
 - pytorch
 - nvidia
 - nodefaults

dependencies:
# Don't do these -- they interfere with NERSC systems
# # conda compilers
# - c-compiler
# - cxx-compiler

 # compilers
 - scons

 # psana
 - psana

 # python
 - python=3.9
 - biopython
 - ipython
 - pybind11
 - setuptools<60
 - msgpack-cxx

 # testing
 - pytest
 - pytest-xdist
 - mock

 # documentation
 - docutils
 - numpydoc
 - sphinx

 # graphics
 - pillow
 - reportlab
 # - wxpython
 - wxpython
 - pyopengl
 - libtiff

 # HDF5 (main libraries come with psana)
 - conda-forge::hdf5
 - conda-forge::h5py
 - conda-forge::hdf5plugin
 
 # other
 - libsvm
 - mrcfile
 - pint
 - psutil
 - conda-forge::nxmx

 # cctbx channel
 - libsvm_py

 # dials
 - jinja2
 - msgpack-python
 - orderedset
 - procrunner
 - python-blosc
 - scikit-learn
 - tqdm
 - eigen
 - dials-data
 - gemmi

 # dxtbx
 - natsort

 # xia2
 - tabulate

 # Phenix
 - send2trash
 - PyRTF

 # xfel gui
 - mysql
 - mysql-connector-python
 - mysql-connector-c
 - mysqlclient
 - sqlite
 
 - pandas

 # perlmutter
 - libglu

# pytorch
 - pytorch::pytorch
 - pytorch::torchvision
 - pytorch::torchaudio
 - pytorch::pytorch-cuda=11.8
 - conda-forge::cudatoolkit=11.8.0

 # Avoid numpy 1.21.[01234]
 # See https://github.com/cctbx/cctbx_project/issues/627
 - numpy=1.20|>=1.21.5
