name: psana_env
channels:
 - defaults
 - lcls-i
 - conda-forge
 - cctbx
 - pytorch
 - nvidia
dependencies:
# Don't do these -- they interfere with NERSC systems
# # conda compilers
# - c-compiler
# - cxx-compiler

 # compilers
 - scons

 # psana
 - psana

 # python
 - python=3.10
 - biopython
 - ipython
 - pybind11
 - setuptools<60
 - msgpack-c

 # testing
 - pytest
 - pytest-xdist
 - mock

 # documentation
 - docutils
 - numpydoc
 - sphinx

 # graphics
 - pillow
 - reportlab
 # - wxpython
 - wxpython
 - pyopengl
 - libtiff

 # HDF5 (main libraries come with psana)
 # - hdf5_plugins                      # [unix]
 # - hdf5-external-filter-plugins  # [unix]
 - hdf5plugin

 # other
 - libsvm
 - mrcfile
 - pint
 - psutil

 # cctbx channel
 - libsvm_py

 # dials
 - jinja2
 - msgpack-python
 - orderedset
 - procrunner
 - python-blosc
 - scikit-learn
 - tqdm
 - eigen
 - dials-data

 # xia2
 - tabulate

 # Phenix
 - send2trash
 - PyRTF

 # xfel gui
 - mysql
 - mysql-connector-python
 - mysql-connector-c
 - mysqlclient
 - sqlite
 
 - pandas

 # perlmutter
 - libglu

 # Avoid numpy 1.21.[01234]
 # See https://github.com/cctbx/cctbx_project/issues/627
 - numpy=1.20|>=1.21.5

 # Pytorch
 - pytorch::pytorch
 - pytorch::torchvision
 - pytorch::torchaudio
 - pytorch::pytorch-cuda=11.7
